spring:
    datasource:
        url: jdbc:mysql://localhost:3307/library?useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                default_schema: library
                dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true

server:
    port: 8087
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    ssl:
        enabled: true
        key-store: classpath:ssl/boivalenko_ssl.p12
        key-store-password: root
        key-store-provider: SunJSSE
        key-store-type: PKCS12

logging:
    level:
        org:
            springframework: info
            springframework.security: info
        root: info
    pattern:
        console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'


